#First stage
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
COPY aution-service/pom.xml auction-service/pom.xml
COPY shared/pom.xml shared/pom.xml
COPY shared/src shared/src
COPY auction-service/src auction-service/src
RUN chmod +x mvnw
RUN ./mvnw clean package -pl acution-service -am -DskipTests

# second stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/auction-service/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","app.jar"]