server:
  port: 8085
  shutdown: graceful

spring:
  application:
    name: payment-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  lifecycle:
    timeout-per-shutdown-phase: 15s

aws:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:}
  region: ${AWS_REGION:us-east-1}

jwt:
  secret: ${JWT_SECRET:dev-secret-change-in-production-key}
